#!/bin/bash

# Script for jenkins to run all the required tests.

PROJECT_DIR="$(dirname $0)"
ORIG_WORKING_DIR=`pwd`

if [ -z "${PIP_DOWNLOAD_CACHE}" ]
then
    PIP_DOWNLOAD_CACHE="$ORIG_WORKING_DIR/.pip_download_cache/"
    mkdir -p $PIP_DOWNLOAD_CACHE
fi

# setup a clean virtual env
VIRTUALENV_DIR="$ORIG_WORKING_DIR/.virtualenv"
if [ -e "$VIRTUALENV_DIR" ]
then
    rm -rf "$VIRTUALENV_DIR"
fi
virtualenv "$VIRTUALENV_DIR"
source "$VIRTUALENV_DIR/bin/activate"

# install requirements
pip install -r "$PROJECT_DIR/requirements.txt"
pip install -r "$PROJECT_DIR/test_requirements.txt"
# making sure we get the patched version for coverage, which works with eventlet
pip install git+https://github.com/newbrough/coverage.git#egg=coverage-3.5.2pl1 -U


# run the tests
cd "$PROJECT_DIR"

py.test --cov-report xml \
    --cov-report html \
    --cov-report term-missing \
    --cov nameko \
    --junitxml="$ORIG_WORKING_DIR/test-results.xml" \
    test/

# get back to where we started
cd "$ORIG_WORKING_DIR"

# jenkins will only understand this custom format, not the default flake8 one.
flake8 "$PROJECT_DIR" --format="%(path)s:%(row)d: %(code)s %(text)s" > "$ORIG_WORKING_DIR/pyflakes.txt"

# move files generated during the test to the current directory
mv "$PROJECT_DIR/coverage.xml" "$ORIG_WORKING_DIR/"

if [ -e "$ORIG_WORKING_DIR/htmlcov" ]
then
    rm -rf "$ORIG_WORKING_DIR/htmlcov"
fi
mv "$PROJECT_DIR/htmlcov" "$ORIG_WORKING_DIR/"

# clean up virtualenv
deactivate
rm -rf "$VIRTUALENV_DIR"

